language: python

dist: trusty
sudo: required

python:
  - "3.4"

env:
  - PGI_VERSION="0.0.10.1"
  - PGI_VERSION="0.0.11.1"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gir1.2-packagekitglib-1.0

install:
  - pip install pgi==$PGI_VERSION

script:
  - python3 test.py
