language: python

sudo: required

python:
  - "3.4"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install gir1.2-packagekitglib-1.0

install:
  - pip install pgi

script:
  - python3 test.py
